config/routes.rb
Rails.application.routes.draw do

  root to: 'wages#menu'
  resources :shifts do
    collection do
      get :start
      get :finish
      get :rest_time_start
      get :rest_time_end
    end
  end

  resources :workers do
    member do
      get :show_time
    end
    get 'search', to: 'workers#search'
  end

  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
} 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :wages do
    collection do
      get :menu
      get :makanai
      get :makanai_edit
      get :makanai_delete
      get :makanai_show
      get :eat
    end
  end
  
end

app/models/wage.rb
class Wage < ApplicationRecord
  belongs_to :shift
  belongs_to :worker

  scope :totals, -> { Wage.all.sum(:total) }
  scope :wage_all, -> { where.not(total: 0)}
  scope :started, -> { where(end_at: nil).order(:start_at) }
end

app/controllers/wages_controller.rb
class WagesController < ApplicationController
  def index
    @wages = Wage.all.includes(:worker)
  end
  def menu
  end
  def makanai
    @wages = Wage.all
    @wage = Wage.new
  end
  def eat
    if 
      @wage = Wage.where(shift_id: wage_params[:shift_id])
      @wage.update(meals: wage_params[:meals])
      redirect_to root_path
      flash[:finish] = '食べました'
    else
      flash.now[:alert] = '食べれませんでした'
      render 'makanai'
    end
  end

  def makanai_edit
    @wages = Wage.all.includes(:worker)
    @wage_name = Wage.select('worker_id')
    # binding.pry
  end
  def makanai_show
  end
  def makanai_delete
  end
  private
  def wage_params
    params.require(:wage).permit(
      # :worker_id,
      :shift_id,
      :meals
    )
  end
end

      

app/helpers/wages_helper.rb
module WagesHelper
end

app/views/wages/makanai.html.haml
.main_wrapper
  .contents
    = render 'shared/header'
  .makanai_main
    = form_with model: @wage, url: eat_wages_path, method: :get, class: 'eat_form', local: true do |f|
      = f.select :shift_id, Shift.all.map { |shift| [shift.start_at.strftime('%Y年%-m月%-d日') + shift.worker.fullname, shift.id] }, :include_blank => '時間と名前'
      -# = f.select :worker_id, Worker.all.map { |worker| [worker.fullname, worker.id] }, :include_blank => '名前'
      = f.select :meals, ['100', '150', '300'], include_blank: '値段'
      = f.submit '食べる', class: 'eat_form__button'
    
    = link_to '食べない', root_path, class: 'home__button'
  .makanai_footer
    %p 2019
    %p sample

  

app/views/wages/makanai_edit.html.haml
.main_wrapper
  .contents
    = render 'shared/header'
  
    %h1.content_name 従業員一覧
    %table
      %tr
        %th 名前
        %th 出勤状態
        %th 扶養残り
        %th 編集・削除
      -# - @wages.each do |worker|
        %tr
          %td 
            = link_to worker.fullname, "/workers/#{worker.id}", class: 'name_box'
          %td
            = link_to '編集', edit_worker_path(worker), class: 'name_box'
        

app/views/wages/menu.html.haml
%nav.menu1
  %input#menu-open.menu-open{:href => "#", :name => "menu-open", :type => "checkbox"}
  %label.menu-open-button{:for => "menu-open"}
    %span.lines.line-1
    %span.lines.line-2
    %span.lines.line-3
  %a.menu-item.blue{:href => "/shifts/new"}
    %h2 勤怠入力
  %a.menu-item.green{:href => "/shifts"}
    %h2 出勤状況
  %a.menu-item.red{:href => "/wages/makanai"}
    %h2 まかない
  %a.menu-item.purple{:href => "/workers/new"}
    %h3 アルバイト登録
  %a.menu-item.orange{:href => "/workers"}
    %h3 アルバイト一覧
  %a.menu-item.lightblue{:href => "/users/sign_in"}
    %h2 ログイン
    