config/routes.rb
Rails.application.routes.draw do

  root to: 'wages#menu'
  resources :shifts do
    collection do
      get :start
      get :finish
      get :rest_time_start
      get :rest_time_end
    end
  end

  resources :workers do
    member do
      get :show_time
    end
    get 'search', to: 'workers#search'
  end

  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
} 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :wages do
    collection do
      get :menu
      get :makanai
      get :makanai_edit
      get :makanai_delete
      get :makanai_show
      get :eat
    end
  end
  
end

app/models/shift.rb
class Shift < ApplicationRecord

  belongs_to :worker
  has_one :wage

  scope :started, -> { where(end_at: nil).order(:start_at) }
  scope :finish, -> { where.not(start_at: nil, end_at: nil) }
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }

  attr_accessor :action_required
  after_save :salary, if: :action_required?

  def day_salary
    if rest_end_at.nil? and rest_start_at.nil?
      s = end_at - start_at
    else
      s = end_at - start_at - ( rest_end_at - rest_start_at )
    end
      h = s / 60 / 60
      @wage = (h * worker.per_hour).round
  end

  def action_required?
    action_required
  end

  private
  def salary
    if rest_end_at.nil? and rest_start_at.nil?
      working_seconds = end_at - start_at
    else
      working_seconds = end_at - start_at - ( rest_end_at - rest_start_at )
    end
    working_hours = working_seconds / 60 / 60
    night_border = DateTime.parse "10:00 pm"
    if working_hours > 8 && night_border < end_at
      base_wage = (8 * worker.per_hour).round
      long_time = working_hours - 8
      long_wage = (worker.per_hour * 1.25 * long_time).round
      night_time = (end_at - night_border) / 60 / 60
      night_wage = (working_hours * 1.5 * night_time)
    elsif night_border < end_at
      night_time = (end_at - night_border) / 60 / 60
      night_wage = (worker.per_hour * 1.25 * night_time).round
      base_time = (night_border - start_at) / 60 / 60
      base_wage = (worker.per_hour * base_time).round
      long_wage = 0
    elsif working_hours > 8
      base_wage = (8 * worker.per_hour).round
      long_time = working_hours - 8
      long_wage = (worker.per_hour * 1.25 * long_time).round
      total_wage = base_wage + long_wage
      night_wage = 0
    else 
      base_wage = (working_hours * worker.per_hour).round  ## 8 >= working_hours
      total_wage = base_wage
      night_wage = 0
      long_wage = 0
    end
    @shift = Shift.finish.last
    @wage = Wage.find_or_initialize_by(id: @shift.id)
    if @wage.new_record? # 新規作成の場合は保存
      @wage.attributes = {base: base_wage, long: long_wage, night: night_wage, total: total_wage, worker_id: @shift.worker_id, shift_id: @shift.id}
      @wage.save
    else
      @wage.update_attributes(base: base_wage, long: long_wage, night: night_wage, total: total_wage, worker_id: @shift.worker_id, shift_id: @shift.id)
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_worker, only: [:start, :finish, :rest_time_start, :rest_time_end]
  
  def index
    @q = Shift.ransack(params[:q])
    @shifts = @q.result(distinct: true).all.includes(:worker)
    @dates = Date.today.all_month
  end
  def new
    @shift = Shift.new
  end
  def create
    @shift = Shift.new(shift_params)
    @shift.save
  end

  def start
    @shift = Shift.new(shift_params)
    if @shift.save
      id = @shift.worker_id
      @worker = Worker.find(id).update_attributes(status: :attendance)
      redirect_to root_path
      flash[:attend] = '出勤しました' 
    else
      flash.now[:alert] = '出勤に失敗しました'
      render 'new'
    end
  end

  def finish
    @shift = Shift.where(params[:worker_id]).started.last
    @shift.end_at = Time.now
    if @shift.action_required = true
      @shift.save!
      id = @shift.worker_id
      @worker = Worker.find(id).update_attributes(status: :un_attendance)
      redirect_to root_path
      flash[:finish] = '退勤しました'
    else
      flash.now[:alert] = '退勤に失敗しました'
      render 'new'
    end
  end

  def rest_time_start
    @shift = Shift.where(params[:worker_id]).started.last
    @shift.rest_start_at = Time.now
    if @shift.save
      id = @shift.worker_id
      @worker = Worker.find(id).update_attributes(status: :rest)
      redirect_to root_path
      flash[:rest_start] = '休憩です'
    else
      flash.now[:alert] = '休憩に失敗しました'
      render 'new'
    end
  end

  def rest_time_end
    @shift = Shift.where(params[:worker_id]).started.last
    @shift.rest_end_at = Time.now
    if @shift.save
      id = @shift.worker_id
      @worker = Worker.find(id).update_attributes(status: :attendance)
      redirect_to root_path
      flash[:rest_end] = '戻りです'
    else
      flash.now[:alert] = '戻りに失敗しました'
      render 'new'
    end
  end

  def edit
    @shift = Shift.find(params[:id])
  end

  def update
    @shift = Shift.find(params[:id])
    if 
      @shift.action_required = true
      @shift.update(shift_params)
      redirect_to shifts_path
      flash[:rest_start] = '勤務時間編集しました'
    else
      render 'edit'
    end
  end

  private 
  def shift_params
    params.require(:shift).permit(
      :worker_id,
      :start_at,
      :end_at,
      :rest_start_at,
      :rest_end_at
    )
  end

  def set_worker
    @worker = Worker.find(params[:worker_id].to_i) if params[:worker_id].present?
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/edit.html.haml
.main_wrapper
  .contents
    = render 'shared/header'

  .form_box
    = form_with model: @shift, url: shift_path, method: :patch, class: 'time_class', local: true do |f|
      .time_class__select
        = f.label '出勤'
        = f.datetime_select :start_at, autofocus: true, date_separator: '/'
      .time_class__select
        = f.label '退勤'
        = f.datetime_select :end_at, autofocus: true, date_separator: '/', discard_year: true
      .time_class__select
        = f.label '休憩'
        = f.datetime_select :rest_start_at, autofocus: true, include_blank: true, date_separator: '/', discard_year: true
      .time_class__select
        = f.label '戻り'
        = f.datetime_select :rest_end_at, autofocus: true, include_blank: true, date_separator: '/', discard_year: true

      .button_box
        = f.submit '登録', class: 'button_box__create'
      .button_box
        = link_to '戻る', shifts_path, class: 'button_box__return'


  

app/views/shifts/index.html.haml
.main_wrapper
  .contents
    = render 'shared/header'

    %h1.content_name 本日の出勤状況
    %table
      %tr
        %th 日時
        %th 出勤
        %th 退勤
        %th 休憩
        %th 戻り
        %th 名前
        %th 出勤状態
        %th 扶養残り
        %th 編集
      - @shifts.created_today.each do |shift|
        %tr
          %td
            = shift.start_at.strftime('%Y年%-m月%-d日') if shift.start_at.present?
          %td
            = shift.start_at.strftime('%-H時%-M分') if shift.start_at.present?
          %td
            = shift.end_at.strftime('%-H時%-M分') if shift.end_at.present?
          %td
            = shift.rest_start_at.strftime('%-H時%-M分') if shift.rest_start_at.present?
          %td
            = shift.rest_end_at.strftime('%-H時%-M分') if shift.rest_end_at.present? 
          %td
            = shift.worker.fullname
          %td
            = t("activerecord.status.#{shift.worker.status}")
          %td
            = number_to_currency(1080000 - shift.worker.wages.totals, :unit => "円")
          %td 
            = link_to '編集', edit_shift_path(shift), class: 'name_box'
      
      
          
            
  
  


        

app/views/shifts/new.html.haml
.main_wrapper
  .contents
    = render 'shared/header'
    .main
      .side
      .clock_flame
        %span#clock_date 
        %span#clock_time 
      .button_flame
        .button_box
          = form_with model: @shift, url: start_shifts_path, method: :get, local: true do |f|
            = f.select :worker_id, Worker.all.map { |worker| [worker.fullname, worker.id] }, :include_blank => '---'
            = f.hidden_field :start_at, value: Time.now
            = f.submit '出勤', class: 'start_button'
        .button_box
          = form_with model: @shift, url: finish_shifts_path, method: :get, local: true do |f|
            = f.select :worker_id, Worker.all.map { |worker| [worker.fullname, worker.id] }, :include_blank => '---'
            = f.submit '退勤', class: 'end_button'
        .button_box
          = form_with model: @shift, url: rest_time_start_shifts_path, method: :get,local: true do |f|
            = f.select :worker_id, Worker.all.map { |worker| [worker.fullname, worker.id] }, :include_blank => '---'
            = f.submit '休憩', class: 'rest_start_button'
        .button_box
          = form_with model: @shift, url: rest_time_end_shifts_path, method: :get,local: true do |f|
            = f.select :worker_id, Worker.all.map { |worker| [worker.fullname, worker.id] }, :include_blank => '---'
            = f.submit '戻り', class: 'rest_end_button'
    .footer
      %p 2019
      %p sample
      