config/routes.rb
Rails.application.routes.draw do

  root to: 'wages#menu'
  resources :shifts do
    collection do
      get :start
      get :finish
      get :rest_time_start
      get :rest_time_end
    end
  end

  resources :workers do
    member do
      get :show_time
    end
    get 'search', to: 'workers#search'
  end

  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
} 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :wages do
    collection do
      get :menu
      get :makanai
      get :makanai_edit
      get :makanai_delete
      get :makanai_show
      get :eat
    end
  end
  
end

app/models/worker.rb
class Worker < ApplicationRecord
  enum status:{attendance: 1,un_attendance: 0,rest: 2}
  has_many :shifts
  has_many :wages, through: :shifts

  def fullname
    first_name + last_name
  end


  VALID_EMAIL_REGIX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/

  # validates :family_name,               presence: true, length: { minimum: 1, maximum: 10}
  # validates :first_name,                presence: true, length: { minimum: 1, maximum: 10}
  # validates :family_name_in_katakana,   presence: true, format: { 
  #                                       with: /\A[\p{katakana}ー－]+\z/, 
  #                                       message: "はカナ文字を入力してください" },
  #                                       length: { minimum: 1, maximum: 15}

  # validates :first_name_in_katakana,    presence: true, format: { 
  #                                       with: /\A[\p{katakana}ー－]+\z/, 
  #                                       message: "はカナ文字を入力してください" },
  #                                       length: { minimum: 1, maximum: 15}
  # validates :tel,                       presence: true, format: { with: VALID_PHONE_REGEX }, numericality: true, allow_blank: true
  # validates :email,                     presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGIX }
  # validates :post_number,               presence: true
  # validates :address,                   presence: true
  # validates :per_hour,                  
  
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only:  [:edit, :update, :destroy]

  def index
    @workers = Worker.all.includes(:shifts, :wages)
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
       redirect_to root_path
    else
       render 'new'
    end
  end

  def show
    @worker = Worker.find_by(id: params[:id])
    @workers = @worker.wages.page(params[:page]).per(8)
  end

  def show_time
    @worker = Worker.find_by(id: params[:id])
    @workers = @worker.shifts.page(params[:page]).per(8)
  end

  def edit
  end

  def update
    if  @worker.update(worker_params)
      redirect_to root_path
      flash[:rest_start] = '編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @worker.destroy
    redirect_to root_path
    flash[:finish] = '削除しました'
  end

private
  def set_worker
    @worker = Worker.find(params[:id])
  end

  def worker_params
    params.require(:worker).permit(
    :first_name,
    :last_name,
    :first_name_kana,
    :last_name_kana,
    :tel,
    :e_mail,
    :post_number,
    :address,
    :per_hour,
    :birthday,
    :classification,
    :authority,
    :hire_date,
    :departure_date
    )
  end    


end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/edit.html.haml
.form-wrapper
  .form-title アルバイト情報登録
  = form_with model: @worker, url: worker_path, method: :patch, local: true do |f|
    .form-item
      = f.email_field :e_mail, autofocus: true, placeholder: 'E_MAIL'
    .form-item
      = f.text_field :first_name, placeholder: '名字 例)山田'
    .form-item
      = f.text_field :last_name, placeholder: '名前 例)太郎'
    .form-item
      = f.text_field :first_name_kana, placeholder: 'フリガナ 例)ヤマダ'
    .form-item
      = f.text_field :last_name_kana, placeholder: 'フリガナ 例)タロウ'
    .form-item
      = f.telephone_field :tel, placeholder: '電話番号 例)09012345678'
    .form-item
      = f.number_field :post_number, placeholder: '郵便番号 例)1234567'
    .form-item
      = f.text_field :address, placeholder: '住所 例)東京都東京市東京町1-1-1'
    .form-item
      = f.text_field :per_hour, placeholder: '時給 例)1000'
    .form-item
      生年月日 例）1990/10/20
      = f.date_field :birthday, placeholder: '生年月日 例）1990/10/20'
    .form-item
      = f.select :classification, ['正社員', '派遣', 'パートタイマー'],
							{ include_blank: '労働者区分' }
    .form-item
      = f.select :authority, ['管理権限者','一般スタッフ'],
							{ include_blank: '権限' }
    .form-item
      入社日 例）2018/1/1
      = f.date_field :hire_date
    .form-item
      退社日 例）2018/6/1
      = f.date_field :departure_date
    .button-panel
      = f.submit 'EDIT', class: 'button'

app/views/workers/index.html.haml
.main_wrapper
  .contents
    = render 'shared/header'
  
    %h1.content_name 従業員一覧
    %table
      %tr
        %th 名前
        %th 出勤状態
        %th 扶養残り
        %th 編集・削除
      - @workers.each do |worker|
        %tr
          %td 
            = link_to worker.fullname, "/workers/#{worker.id}", class: 'name_box'
          %td 
            = t("activerecord.status.#{worker.status}")
          %td 
            = number_to_currency(1080000 - worker.wages.totals, :unit => "円")
          %td
            = link_to '編集', edit_worker_path(worker), class: 'name_box'
            = link_to '削除', worker_path(worker), method: :delete, class: 'name_box', data: { confirm: '本当に削除しますか？' }
        
  

app/views/workers/new.html.haml
.form-wrapper
  .form-title アルバイト情報登録
  = form_with model: @worker, url: workers_path, method: :post, local: true do |f|
    .form-item
      = f.email_field :e_mail, autofocus: true, placeholder: 'E_MAIL'
    .form-item
      = f.text_field :first_name, placeholder: '名字 例)山田'
    .form-item
      = f.text_field :last_name, placeholder: '名前 例)太郎'
    .form-item
      = f.text_field :first_name_kana, placeholder: 'フリガナ 例)ヤマダ'
    .form-item
      = f.text_field :last_name_kana, placeholder: 'フリガナ 例)タロウ'
    .form-item
      = f.telephone_field :tel, placeholder: '電話番号 例)09012345678'
    .form-item
      = f.number_field :post_number, placeholder: '郵便番号 例)1234567'
    .form-item
      = f.text_field :address, placeholder: '住所 例)東京都東京市東京町1-1-1'
    .form-item
      = f.text_field :per_hour, placeholder: '時給 例)1000'
    .form-item
      生年月日 例）1990/10/20
      = f.date_field :birthday, placeholder: '生年月日 例）1990/10/20'
    .form-item
      = f.select :classification, ['正社員', '派遣', 'パートタイマー'],
							{ include_blank: '労働者区分' }
    .form-item
      = f.select :authority, ['管理権限者','一般スタッフ'],
							{ include_blank: '権限' }
    .form-item
      入社日 例）2018/1/1
      = f.date_field :hire_date
    .form-item
      退社日 例）2018/6/1
      = f.date_field :departure_date
    .button-panel
      = f.submit 'CREATE', class: 'button'
      = link_to 'HOME', root_path, class: 'back-button'

app/views/workers/show.html.haml
.main_wrapper
  .contents
    = render 'shared/header'

    %h1.content_name= @worker.fullname + ' 給料'
    %table
      %tr
        %th 日付
        %th 基本給
        %th 超勤
        %th 深夜
        %th 合計
        %th まかない
      - @workers.each do |wage|
        %tr
          %td= wage.created_at.strftime('%Y/%m/%d')
          %td= wage.base
          %td= wage.long
          %td= wage.night
          %td= wage.total
          %td= wage.meals
    .button_box
      =link_to '時間', show_time_worker_path, class: 'button_box__time'
= paginate @workers

      

    


    
  
  

app/views/workers/show_time.html.haml
.main_wrapper
  .contents
    = render 'shared/header'

    %h1.content_name= @worker.fullname + ' 勤務時間'
    %table
      %tr
        %th 日時
        %th 出勤
        %th 退勤
        %th 休憩
        %th 戻り
        %th 編集
      - @workers.each do |shift|
        %tr
          %td
            = shift.start_at.strftime('%Y年%-m月%-d日') if shift.start_at.present?
          %td
            = shift.start_at.strftime('%-H時%-M分') if shift.start_at.present?
          %td
            = shift.end_at.strftime('%-H時%-M分') if shift.end_at.present?
          %td
            = shift.rest_start_at.strftime('%-H時%-M分') if shift.rest_start_at.present?
          %td
            = shift.rest_end_at.strftime('%-H時%-M分') if shift.rest_end_at.present? 
          %td 
            = link_to '編集', edit_shift_path(shift), class: 'name_box'
    .button_box
      =link_to '戻る', worker_path, class: 'button_box__time'
= paginate @workers